name: ai_book_summary_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0 

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  dio: ^5.9.0
  get: ^4.7.2
  get_it: ^8.2.0
  pretty_dio_logger: ^1.4.0
  intl: ^0.18.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
